"""initial_schema

Revision ID: 06dbc42f459a
Revises:
Create Date: 2026-05-11 20:00:25.851323

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06dbc42f459a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_active", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "congresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "legislators",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=300), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("nick_name", sa.String(length=100), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("district", sa.String(length=200), nullable=True),
        sa.Column("province", sa.String(length=100), nullable=True),
        sa.Column("chamber", sa.String(length=20), nullable=True),
        sa.Column("wikidata_id", sa.String(length=20), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parties",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("abbreviation", sa.String(length=20), nullable=True),
        sa.Column("wikidata_id", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bills",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("bill_no", sa.String(length=50), nullable=True),
        sa.Column("bill_no_f", sa.String(length=50), nullable=True),
        sa.Column("session_no", sa.String(length=50), nullable=True),
        sa.Column("title_full", sa.Text(), nullable=False),
        sa.Column("title_short", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("chamber", sa.String(length=20), nullable=True),
        sa.Column("congress_id", sa.Integer(), nullable=False),
        sa.Column("significance_code", sa.Integer(), nullable=True),
        sa.Column("significance_desc", sa.String(length=50), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("status_order", sa.Numeric(), nullable=True),
        sa.Column("date_filed", sa.Date(), nullable=True),
        sa.Column("date_signed", sa.Date(), nullable=True),
        sa.Column("date_vetoed", sa.Date(), nullable=True),
        sa.Column("mother_bill_no", sa.String(length=50), nullable=True),
        sa.Column("mother_status", sa.Text(), nullable=True),
        sa.Column("text_as_filed", sa.Text(), nullable=True),
        sa.Column("committee", sa.String(length=200), nullable=True),
        sa.Column("topic_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("has_pdf", sa.Boolean(), nullable=True),
        sa.Column("pdf_version", sa.String(length=20), nullable=True),
        sa.Column("pdf_word_count", sa.Integer(), nullable=True),
        sa.Column("pdf_parsed_at", sa.DateTime(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["congress_id"],
            ["congresses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("feedback", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "congress_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("legislator_id", sa.String(length=50), nullable=False),
        sa.Column("congress_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.String(length=50), nullable=True),
        sa.Column("chamber", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["congress_id"],
            ["congresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legislator_id", "congress_id", name="uq_member_congress"),
    )
    op.create_table(
        "bill_authorships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bill_id", sa.String(length=50), nullable=False),
        sa.Column("legislator_id", sa.String(length=50), nullable=False),
        sa.Column("is_coauthor", sa.Boolean(), nullable=True),
        sa.Column("sequence_no", sa.Integer(), nullable=True),
        sa.Column("journal_no", sa.String(length=50), nullable=True),
        sa.Column("name_code", sa.String(length=100), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bill_id", "legislator_id", "is_coauthor", name="uq_bill_author"
        ),
    )
    op.create_table(
        "votes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bill_id", sa.String(length=50), nullable=False),
        sa.Column("legislator_id", sa.String(length=50), nullable=False),
        sa.Column("vote", sa.String(length=20), nullable=False),
        sa.Column("vote_stage", sa.String(length=50), nullable=True),
        sa.Column("vote_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bill_id", "legislator_id", "vote_stage", name="uq_vote"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes")
    op.drop_table("bill_authorships")
    op.drop_table("congress_memberships")
    op.drop_table("chat_messages")
    op.drop_table("bills")
    op.drop_table("parties")
    op.drop_table("legislators")
    op.drop_table("congresses")
    op.drop_table("chat_sessions")
    # ### end Alembic commands ###
